version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

kos:
  - tags:
      - "{{.Version}}"
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64

nfpms:
  - maintainer: Drummer <drum-roll@example.com>
    license: BSD 2-Clause
    description: some description
    formats:
    - deb
    - rpm
    contents:
    - src: ./systemd/system/testrelease.service
      dst: /usr/lib/systemd/system/testrelease.service
