version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

kos:
  - tags:
      - "{{.Version}}"
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64

nfpms:
  - maintainer: Drummer <drum-roll@example.com>
    license: BSD 2-Clause
    description: |
      FooBar is the great foo and bar software.
        And this can be in multiple lines!
    vendor: "a vendor"
    homepage: "http://example.com"
    section: "misc"
    formats:
    - deb
    - rpm
    contents:
    - src: ./systemd/system/testrelease.service
      dst: /usr/lib/systemd/system/testrelease.service
    - src: .lintian-overrides
      dst: ./usr/share/lintian/overrides/testrelease
      packager: deb
      file_info:
        mode: 0644
    - src: ./LICENSE
      dst: /usr/share/doc/testrelease/copyright
      packager: deb
      file_info:
        mode: 0644
